import { ProductCondition, type Product } from '@/types';

export const sampleProducts: Product[] = [
  {
    id: 'prod-1',
    sellerId: 'seller-1',
    name: 'Ankara Wrap Maxi Skirt',
    description: 'Handcrafted authentic African Ankara wax print wrap skirt. Rich vibrant patterns, adjustable waist ties, and flattering silhouette for casual and festive occasions.',
    category: 'Clothing',
    price: 8500,
    originalPrice: 15000,
    images: [
      'https://images.unsplash.com/photo-1614081781451-29c084a7de30?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80',
    ],
    size: 'M',
    condition: ProductCondition.NEW,
    material: '100% Cotton Wax Print',
    color: 'Multi / Gold',
    brand: 'Lagos Heritage',
    quantity: 12,
    sold: 45,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-01'),
    updatedAt: new Date('2026-08-15'),
  },
  {
    id: 'prod-2',
    sellerId: 'seller-2',
    name: 'Genuine Leather Tote Handbag',
    description: 'Structured premium leather shoulder handbag with reinforced handles. Spacious interior with multiple zip pockets, perfect for work, meetings, or shopping.',
    category: 'Bags',
    price: 18000,
    originalPrice: 32000,
    images: [
      '/bag-handbag.jpg',
    ],
    size: 'Medium',
    condition: ProductCondition.LIKE_NEW,
    material: 'Genuine Leather',
    color: 'Rich Brown',
    brand: 'Yaba Classics',
    quantity: 5,
    sold: 28,
    rating: 4.8,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-10'),
    updatedAt: new Date('2026-08-16'),
  },
  {
    id: 'prod-3',
    sellerId: 'seller-3',
    name: 'Chop Corporate Shoes',
    description: 'Comfort meets class. Handcrafted corporate leather lace-up shoes. Flexible anti-slip rubber sole, all-day cushioned insole, and timeless sleek finish for professionals.',
    category: 'Shoes',
    price: 22999,
    originalPrice: 38000,
    images: [
      '/male-shoes-collection.jpg',
    ],
    size: '42',
    condition: ProductCondition.NEW,
    material: 'Full-Grain Leather',
    color: 'Black / Brown / Grey',
    brand: 'Executive Walk',
    quantity: 14,
    sold: 62,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-12'),
    updatedAt: new Date('2026-08-18'),
  },
  {
    id: 'prod-4',
    sellerId: 'seller-4',
    name: 'Folded Office Shirts Pack',
    description: 'Clean, classy, and comfortable. Pack of crisp office shirts in classic stripes and solid blues. Neatly folded, premium breathable cotton with stiff collar.',
    category: 'Shirts',
    price: 9999,
    originalPrice: 20000,
    images: [
      '/folded-shirts-blue.jpg',
      '/casual-shirts-stack.jpg',
    ],
    size: 'L',
    condition: ProductCondition.LIKE_NEW,
    material: 'Crisp Cotton',
    color: 'Sky Blue / Striped',
    brand: 'Savile Row Thrift',
    quantity: 15,
    sold: 89,
    rating: 4.8,
    trending: true,
    published: true,
    createdAt: new Date('2026-07-29'),
    updatedAt: new Date('2026-08-10'),
  },
  {
    id: 'prod-5',
    sellerId: 'seller-5',
    name: 'Executive Two-Piece Suit & Tie',
    description: 'Look rich, spend smart. Tailored two-piece slim fit business suit complete with matching blue necktie and pocket square. Premium wool-blend with immaculate cut.',
    category: 'Suits',
    price: 28500,
    originalPrice: 55000,
    images: [
      '/suit-blue-1.jpg',
      '/suit-grey-1.jpg',
    ],
    size: '42R / L',
    condition: ProductCondition.LIKE_NEW,
    material: 'Wool Blend',
    color: 'Midnight Navy',
    brand: 'Executive Suitmakers',
    quantity: 6,
    sold: 34,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-11'),
    updatedAt: new Date('2026-08-17'),
  },
  {
    id: 'prod-6',
    sellerId: 'seller-6',
    name: 'Chop Casuals Shirt Stack',
    description: 'Look sharp, chop casuals! Premium quality folded casual shirts in versatile colors. Soft on the skin, breathable fabric, durable double stitching, and built for everyday style.',
    category: 'Shirts',
    price: 9999,
    originalPrice: 18000,
    images: [
      '/casual-shirts-colorful.jpg',
      '/casual-shirts-stack.jpg',
    ],
    size: 'Mixed (M & L)',
    condition: ProductCondition.GOOD,
    material: '100% Breathable Cotton',
    color: 'Multi Assorted',
    brand: 'Street Edit',
    quantity: 20,
    sold: 72,
    rating: 4.7,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-07'),
    updatedAt: new Date('2026-08-14'),
  },
  {
    id: 'prod-7',
    sellerId: 'seller-7',
    name: 'Vintage Washed Denim Jeans',
    description: 'Straight-leg vintage wash denim jeans with sturdy brass rivets. Classic five-pocket styling, heavy-duty denim weave, and timeless streetwear look.',
    category: 'Clothing',
    price: 12500,
    originalPrice: 24000,
    images: [
      '/jeans-folded.jpg',
      '/jeans-stack.jpg',
    ],
    size: '32 / 34',
    condition: ProductCondition.GOOD,
    material: 'Heavyweight Denim',
    color: 'Classic Indigo Blue',
    brand: "Levi's Thrift Pick",
    quantity: 16,
    sold: 58,
    rating: 4.6,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-05'),
    updatedAt: new Date('2026-08-12'),
  },
  {
    id: 'prod-8',
    sellerId: 'seller-8',
    name: 'Classic Black Stiletto Heels',
    description: 'Sleek pointed-toe black high heels with padded insole and slender heel. Premium patent finish suited for corporate wear, dinners, and events.',
    category: 'Shoes',
    price: 16000,
    originalPrice: 28000,
    images: [
      '/heels-black-pair.jpg',
      '/heels-black-single.jpg',
    ],
    size: '39',
    condition: ProductCondition.LIKE_NEW,
    material: 'Patent Faux Leather',
    color: 'Glossy Black',
    brand: 'Zara Thrift',
    quantity: 8,
    sold: 41,
    rating: 4.8,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-08'),
    updatedAt: new Date('2026-08-15'),
  },
  {
    id: 'prod-9',
    sellerId: 'seller-9',
    name: "Traditional Men's Agbada 3-Piece Set",
    description: 'Magnificent embroidered 3-piece Agbada attire including outer robe, buba shirt, and matching sokoto trousers. Intricate royal neckline embroidery.',
    category: 'Clothing',
    price: 35000,
    originalPrice: 65000,
    images: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1614081781451-29c084a7de30?auto=format&fit=crop&w=900&q=80',
    ],
    size: 'XL',
    condition: ProductCondition.NEW,
    material: 'Damask & Cashmere',
    color: 'Pristine White / Gold',
    brand: 'Yoruba Royal Wardrobe',
    quantity: 4,
    sold: 21,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-09'),
    updatedAt: new Date('2026-08-16'),
  },
  {
    id: 'prod-10',
    sellerId: 'seller-10',
    name: 'Handmade African Beaded Collar Necklace',
    description: 'Intricately hand-strung glass beaded collar necklace handcrafted by Nigerian artisans. Traditional geometric motifs that elevate both modern and ethnic outfits.',
    category: 'Accessories',
    price: 4500,
    originalPrice: 9000,
    images: [
      'https://images.unsplash.com/photo-1614081781451-29c084a7de30?auto=format&fit=crop&w=900&q=80',
    ],
    size: 'Adjustable',
    condition: ProductCondition.NEW,
    material: 'Glass Beads & Brass Clasp',
    color: 'Multi-color Gold & Coral',
    brand: 'AfriJewels Lagos',
    quantity: 25,
    sold: 120,
    rating: 4.7,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-03'),
    updatedAt: new Date('2026-08-11'),
  },
  {
    id: 'prod-11',
    sellerId: 'seller-11',
    name: 'Luxury Silk Lace Boubou Gown',
    description: 'Breathtaking floor-length royal Boubou gown with delicate scalloped lace embroidery, sparkling crystal buttons, and free-flowing elegant drape.',
    category: 'Clothing',
    price: 26000,
    originalPrice: 48000,
    images: [
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=900&q=80',
    ],
    size: 'Free Size',
    condition: ProductCondition.NEW,
    material: 'Swiss Voile & Silk Lace',
    color: 'Emerald & Gold',
    brand: 'African Queen Couture',
    quantity: 7,
    sold: 42,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-06'),
    updatedAt: new Date('2026-08-13'),
  },
  {
    id: 'prod-12',
    sellerId: 'seller-12',
    name: "Women's Pointed Ballet Flats",
    description: 'Comfortable everyday pointed slip-on flats. Cushioned inner sole, flexible grip bottom, and sleek silhouette suitable for office or casual outings.',
    category: 'Shoes',
    price: 13500,
    originalPrice: 22000,
    images: [
      '/female-shoe-flat.jpg',
    ],
    size: '39 / 40',
    condition: ProductCondition.NEW,
    material: 'Soft Faux Leather',
    color: 'Tan Beige',
    brand: 'Chic Steps',
    quantity: 11,
    sold: 37,
    rating: 4.7,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-04'),
    updatedAt: new Date('2026-08-10'),
  },
  {
    id: 'prod-13',
    sellerId: 'seller-3',
    name: 'Retro Street High Top Sneakers',
    description: 'Iconic street style high-top sneakers. Padded ankle collar, premium dual-tone leather overlay, and cushioned impact sole for all-day comfort.',
    category: 'Sneakers',
    price: 24500,
    originalPrice: 38000,
    images: [
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80',
    ],
    size: '43',
    condition: ProductCondition.LIKE_NEW,
    material: 'Full-Grain Leather & Rubber',
    color: 'Red / White / Black',
    brand: 'Air Street Vintage',
    quantity: 8,
    sold: 54,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-14'),
    updatedAt: new Date('2026-08-20'),
  },
  {
    id: 'prod-14',
    sellerId: 'seller-3',
    name: 'Pro Runner Cushioned Trainers',
    description: 'Ultra-lightweight breathable mesh trainers. Shock-absorbing foam midsole, flexible arch support, and anti-slip traction built for commuting and workouts.',
    category: 'Trainers',
    price: 18900,
    originalPrice: 28000,
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
    ],
    size: '42 / 43',
    condition: ProductCondition.NEW,
    material: 'Engineered Mesh & EVA Foam',
    color: 'Triple Black',
    brand: 'Acro Athletics',
    quantity: 14,
    sold: 41,
    rating: 4.8,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-13'),
    updatedAt: new Date('2026-08-19'),
  },
  {
    id: 'prod-15',
    sellerId: 'seller-5',
    name: 'Italian Silk Necktie & Pocket Square Pack',
    description: 'Executive 3-pack 100% woven silk formal ties with matching pocket squares and tie clip. Crisp knot recovery and stain-resistant finish.',
    category: 'Ties',
    price: 8500,
    originalPrice: 15000,
    images: [
      '/banner-suit-tie.jpg',
    ],
    size: 'Standard Width',
    condition: ProductCondition.NEW,
    material: '100% Mulberry Silk',
    color: 'Navy / Burgundy / Gold',
    brand: 'Savile Row Lagos',
    quantity: 20,
    sold: 76,
    rating: 4.9,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-09'),
    updatedAt: new Date('2026-08-16'),
  },
  {
    id: 'prod-16',
    sellerId: 'seller-4',
    name: 'Formal Stretch Flat-Front Pant Trousers',
    description: 'Tailored comfort stretch corporate pant trousers. Wrinkle-resistant weave, hidden elastic flex waistband, and modern slim-straight taper.',
    category: 'Pant Trousers',
    price: 11500,
    originalPrice: 19000,
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80',
    ],
    size: '34 / 36',
    condition: ProductCondition.LIKE_NEW,
    material: 'Poly-Viscose Stretch Twill',
    color: 'Charcoal Grey',
    brand: 'City Tailors',
    quantity: 18,
    sold: 83,
    rating: 4.8,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-10'),
    updatedAt: new Date('2026-08-18'),
  },
  {
    id: 'prod-17',
    sellerId: 'admin-official',
    name: 'Pro Wireless ANC Earbuds (Noise Cancelling)',
    description: 'High-fidelity Bluetooth wireless earbuds with active noise cancellation, punchy bass, crystal-clear quad mic calls, and 30-hour battery life with charging case.',
    category: 'Gadgets',
    price: 16500,
    originalPrice: 28000,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'Compact',
    condition: ProductCondition.NEW,
    material: 'Matte Polymer & Silicone Tips',
    color: 'Matte Black',
    brand: 'SoundPulse NG',
    quantity: 25,
    sold: 112,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-15'),
    updatedAt: new Date('2026-08-22'),
  },
  {
    id: 'prod-18',
    sellerId: 'admin-official',
    name: 'Refurbished Apple MacBook Pro 13" (Core i5, 256GB SSD)',
    description: 'Vetted Grade A certified pre-owned MacBook Pro. Stunning Retina display, 8GB RAM, 256GB lightning SSD, 8-hour battery health verified, and includes original MagSafe charger.',
    category: 'Laptops',
    price: 195000,
    originalPrice: 260000,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    ],
    size: '13.3-inch',
    condition: ProductCondition.LIKE_NEW,
    material: 'Aluminum Unibody',
    color: 'Space Grey',
    brand: 'Apple Tech Hub',
    quantity: 4,
    sold: 19,
    rating: 5.0,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-12'),
    updatedAt: new Date('2026-08-21'),
  },
  {
    id: 'prod-19',
    sellerId: 'admin-official',
    name: 'YabaRight Thrift Trade-In / Swap Exchange Voucher',
    description: 'Got clean thrift clothes, sneakers, or gadgets you no longer wear? Trade them in for verified YabaRight store vouchers to upgrade your wardrobe with zero stress.',
    category: 'Trade',
    price: 15000,
    originalPrice: 20000,
    images: [
      '/banner-promo-wide.jpg',
    ],
    size: 'Digital Voucher',
    condition: ProductCondition.NEW,
    material: 'Instant Store Credit',
    color: 'Gold Pass',
    brand: 'YabaRight Swap',
    quantity: 50,
    sold: 95,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-01'),
    updatedAt: new Date('2026-08-20'),
  },
  {
    id: 'prod-20',
    sellerId: 'admin-official',
    name: 'Customized Club / Country Jersey (Name & Number Print)',
    description: 'Customized breathable sport jersey with your preferred name and squad number printed in official vinyl. Ideal personalized gift for birthdays, football fans, and loved ones.',
    category: 'Gift Items',
    price: 12500,
    originalPrice: 20000,
    images: [
      'https://images.unsplash.com/photo-1577223625816-7546f13df25d?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'Customized (S-XXL)',
    condition: ProductCondition.NEW,
    material: 'Dri-FIT Breathable Polyester',
    color: 'Custom Jersey Color',
    brand: 'Custom Gift Studio',
    quantity: 30,
    sold: 140,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-15'),
    updatedAt: new Date('2026-08-22'),
  },
  {
    id: 'prod-21',
    sellerId: 'admin-official',
    name: 'Custom Photo & Personal Message Ceramic Mug',
    description: 'High-grade 11oz glossy ceramic mug customized with personal photos, names, or inspirational quotes. Dishwasher and microwave safe. Comes in an elegant gift box.',
    category: 'Gift Items',
    price: 4500,
    originalPrice: 7500,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ],
    size: '11oz / 330ml',
    condition: ProductCondition.NEW,
    material: 'Sublimation Ceramic',
    color: 'White & Custom Print',
    brand: 'Yaba Prints',
    quantity: 45,
    sold: 210,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-16'),
    updatedAt: new Date('2026-08-23'),
  },
  {
    id: 'prod-22',
    sellerId: 'admin-official',
    name: 'Personalized Heavyweight Cotton Graphic T-Shirt',
    description: 'Custom print graphic or name t-shirt on 240GSM heavyweight 100% cotton. Crisp high-definition screen/DTF print built to last through dozens of washes without cracking.',
    category: 'Gift Items',
    price: 7999,
    originalPrice: 12000,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'M / L / XL',
    condition: ProductCondition.NEW,
    material: '100% Combed Cotton',
    color: 'Black / White / Beige',
    brand: 'Custom Gift Studio',
    quantity: 35,
    sold: 88,
    rating: 4.8,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-14'),
    updatedAt: new Date('2026-08-22'),
  },
  {
    id: 'prod-23',
    sellerId: 'admin-official',
    name: 'Custom Embroidered Monogram Streetwear Cap',
    description: 'High-profile structured 6-panel snapback cap featuring personalized 3D puff embroidery of your initials or custom logo. Adjustable brass buckle strap.',
    category: 'Gift Items',
    price: 6500,
    originalPrice: 10000,
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'Adjustable',
    condition: ProductCondition.NEW,
    material: 'Cotton Chino Twill',
    color: 'Black / Khaki',
    brand: 'Yaba Prints',
    quantity: 40,
    sold: 95,
    rating: 4.8,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-15'),
    updatedAt: new Date('2026-08-21'),
  },
  {
    id: 'prod-24',
    sellerId: 'admin-official',
    name: 'Personalized Monogram Shockproof Phone Case',
    description: 'Military-grade drop-tested TPU phone case with custom printed name, initial, or photo. Available for iPhone and Samsung models with raised camera bezels.',
    category: 'Gift Items',
    price: 4999,
    originalPrice: 8500,
    images: [
      'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'All Phone Models',
    condition: ProductCondition.NEW,
    material: 'Hybrid Shockproof TPU',
    color: 'Clear / Matte Black',
    brand: 'Custom Gift Studio',
    quantity: 50,
    sold: 130,
    rating: 4.9,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-16'),
    updatedAt: new Date('2026-08-22'),
  },
  {
    id: 'prod-25',
    sellerId: 'admin-official',
    name: 'Executive Debossed Leather Document Folder',
    description: 'Luxury faux leather presentation folder with magnetic closure, notepad slot, pen holder, and custom laser-engraved nameplate for corporate gifts and grads.',
    category: 'Gift Items',
    price: 9500,
    originalPrice: 16000,
    images: [
      'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'A4 Size',
    condition: ProductCondition.NEW,
    material: 'PU Vegan Leather',
    color: 'Midnight Black / Cognac Brown',
    brand: 'Executive Stationery',
    quantity: 20,
    sold: 45,
    rating: 4.8,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-10'),
    updatedAt: new Date('2026-08-19'),
  },
  {
    id: 'prod-26',
    sellerId: 'admin-official',
    name: 'Hardcover Gold-Foil Journal & Book Gift Set',
    description: 'Custom personalized 200-page lined ribbon journal with gold foil lettering on linen cover. Paired with a sleek bookmark and commemorative gift sleeve.',
    category: 'Gift Items',
    price: 5500,
    originalPrice: 9000,
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'A5 Hardcover',
    condition: ProductCondition.NEW,
    material: 'Linen Hardcover & 100GSM Paper',
    color: 'Emerald & Gold',
    brand: 'Lagos Heritage Books',
    quantity: 25,
    sold: 62,
    rating: 4.9,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-12'),
    updatedAt: new Date('2026-08-20'),
  },
  {
    id: 'prod-27',
    sellerId: 'admin-official',
    name: 'Laser-Engraved Executive Gold-Trim Pen Gift Box',
    description: 'Heavyweight brass ballpoint pen with 24K gold-tone clip and laser-etched custom name or monogram. Comes with 2 refill ink cartridges and velvet-lined presentation box.',
    category: 'Gift Items',
    price: 4500,
    originalPrice: 7500,
    images: [
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'Standard Pen',
    condition: ProductCondition.NEW,
    material: 'Brass & Gold Finish',
    color: 'Matte Black & Gold',
    brand: 'Crown Writing Instruments',
    quantity: 60,
    sold: 175,
    rating: 5.0,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-15'),
    updatedAt: new Date('2026-08-22'),
  },
  {
    id: 'prod-28',
    sellerId: 'admin-official',
    name: 'Custom Name Magnetic Couple Charm Bracelets',
    description: 'Set of 2 handcrafted matte onyx & howlite bead bracelets with engraved stainless steel custom names and magnetic interlocking charm.',
    category: 'Gift Items',
    price: 5999,
    originalPrice: 9500,
    images: [
      'https://images.unsplash.com/photo-1611591475837-7f8976b97664?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'Elastic Stretch (One Size)',
    condition: ProductCondition.NEW,
    material: 'Natural Stone Beads & Stainless Steel',
    color: 'Black & White Duo',
    brand: 'LoveBonds Lagos',
    quantity: 35,
    sold: 110,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-16'),
    updatedAt: new Date('2026-08-23'),
  },
  {
    id: 'prod-29',
    sellerId: 'seller-1',
    name: 'Royal Blue Swiss Voile Lace Aso Ebi (5 Yards)',
    description: 'ASO EBI MADE EASY! Premium Swiss voile cotton lace with shimmering metallic cord embroidery and scalloped borders. Perfect for wedding guest groups, owambe parties, and traditional ceremonies.',
    category: 'Aso Ebi',
    price: 34500,
    originalPrice: 55000,
    images: [
      'https://images.unsplash.com/photo-1614081781451-29c084a7de30?auto=format&fit=crop&w=800&q=80',
    ],
    size: '5 Yards Fabric Bundle',
    condition: ProductCondition.NEW,
    material: '100% Swiss Voile Lace',
    color: 'Royal Blue & Silver',
    brand: 'Zainab Aso Ebi Hub',
    quantity: 15,
    sold: 85,
    rating: 5.0,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-11'),
    updatedAt: new Date('2026-08-21'),
  },
  {
    id: 'prod-30',
    sellerId: 'seller-1',
    name: 'Emerald Green Velvet Sequin Lace Fabric (5 Yards)',
    description: 'ASO EBI MADE EASY! Rich velvet base embellished with micro sequins and heavy 3D floral threadwork. Drapes luxuriously for modern corseted gowns and royal Nigerian party attire.',
    category: 'Aso Ebi',
    price: 38000,
    originalPrice: 62000,
    images: [
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80',
    ],
    size: '5 Yards Fabric Bundle',
    condition: ProductCondition.NEW,
    material: 'Stretch Velvet & Sequin Lace',
    color: 'Emerald Green',
    brand: 'Zainab Aso Ebi Hub',
    quantity: 12,
    sold: 64,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-13'),
    updatedAt: new Date('2026-08-20'),
  },
  {
    id: 'prod-31',
    sellerId: 'seller-11',
    name: 'Luxury Auto-Gele Pre-Tied Headtie & Ipele Set',
    description: 'ASO EBI MADE EASY! Handcrafted pre-tied auto-gele with adjustable velcro back closure and matching shoulder Ipele cloth. Instant owambe perfection without the frustration of manual tying.',
    category: 'Aso Ebi',
    price: 15500,
    originalPrice: 24000,
    images: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    ],
    size: 'Adjustable Auto-Fit',
    condition: ProductCondition.NEW,
    material: 'Aso-Oke & Metallic Thread',
    color: 'Rose Gold & Coral',
    brand: 'African Queen Couture',
    quantity: 20,
    sold: 92,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-14'),
    updatedAt: new Date('2026-08-22'),
  },
  {
    id: 'prod-32',
    sellerId: 'seller-5',
    name: "Men's Cashmere Agbada Fabric & Embroidered Cap Set",
    description: 'ASO EBI MADE EASY! Premium 4-yard soft-flow cashmere wool blend fabric for men’s Agbada, paired with matching hand-embroidered Fila cap. Smooth drape that holds sharp crease lines.',
    category: 'Aso Ebi',
    price: 29500,
    originalPrice: 48000,
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
    ],
    size: '4 Yards Fabric + Cap (Size 7-8)',
    condition: ProductCondition.NEW,
    material: 'Cashmere Wool Blend',
    color: 'Pewter Grey / Navy',
    brand: 'Savile Row Lagos',
    quantity: 10,
    sold: 48,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-15'),
    updatedAt: new Date('2026-08-23'),
  },
];

export const getProductById = (productId: string) =>
  sampleProducts.find((product) => product.id === productId);
